name: Fetch 10-Year Gilt Yield

on:
  schedule:
    - cron: '30 7 * * *'  # 7:30 AM UTC every day
  workflow_dispatch:  # Allow manual runs

jobs:
  fetch-yield:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
        
    - name: Fetch yield data
      run: python fetch_gilt_yield.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add yield.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update gilt yield data"
        git push
